# Generated by Django 3.0.5 on 2020-06-12 19:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opiekun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_opiekun', models.CharField(max_length=200)),
                ('nazwisko_opiekun', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Praca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temat_praca', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wydzial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_wydzial', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Uczen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_uczen', models.CharField(max_length=200)),
                ('nazwisko_uczen', models.CharField(max_length=200)),
                ('indeks_uczen', models.IntegerField(default=0)),
                ('wydzial_uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Wydzial')),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termin_praca', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('opiekun_praca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('temat_praca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Praca')),
                ('uczen_praca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.Uczen')),
            ],
        ),
    ]
